# This is a Taotie configuration file

# The default base branch to run Taotie on
baseBranch: main

# Execution command to run
exec: yarn taotie:fix

# Show interactive comment
commentInteractive: true

# Close the comment on issue dashboard
commentClose: true
